Домашнее задание (верстка)
htmlacademy-htmlcss/323345-device-1 pull request #3
Opened 2023-08-25 09:47 UTC by licos87

На проверку, верстка сайта

2023-08-27 08:57 UTC, vadimrahmanov requested changes
Пересмотри форматы изображений, которые экспортировал из фигмы, когда будешь проходить соответствующий раздел.

2023-08-27 08:57 UTC, vadimrahmanov commented on index.html
> +      </section>
Карточки должны быть вместе с кнопками переключателями в одной секции.
А не отдельная секция для каждой карточки

2023-08-27 08:57 UTC, vadimrahmanov commented on index.html
> +          <li><button class="credit">Кредит</button></li>
У кнопок отсутствует атрибут `type`

2023-08-27 08:57 UTC, vadimrahmanov commented on index.html
> +      <button class="delivery-button"><span><img class="delivery-car" src="image/icon/delivery.svg" alt="Грузовик" width="125" height="100">Доставим редкий товар под заказ<img class="delivery-info" s
Атрибут `type` отсутствует.
Оборачивать изображения в `span` не нужно.
Декоративное изображение. Нужно убрать из разметки.
Переносы.

2023-08-27 08:57 UTC, vadimrahmanov commented on index.html
> +              <a href="#close" title="Close" class="close">×</a>
Это должна быть кнопка, а не ссылка. Ссылки ведут на другие страницы.

2023-08-27 08:57 UTC, vadimrahmanov commented on index.html
> +                <span class="form-product-quantity">-</span>
`+` и `-` кнопки, а не просто текст.

2023-08-27 08:57 UTC, vadimrahmanov commented on index.html
> +      </div>
Модальные окна верстаются в самом конце файла, под подвалом.

2023-08-27 08:57 UTC, vadimrahmanov commented on index.html
> +        <h3 class="about-us-title">О нас</h3>
У заголовков секций всегда используется `H2` (заголовки второго уровня)

2023-08-27 08:57 UTC, vadimrahmanov commented on index.html
> +          <li class="delivery-select-link"><a href="#"><b>ТоксБерри</b></a></li>
Переносы.
Тэг `<b>` устаревший, вместо него нужно использовать `<strong>`
Почему ссылки, а не просто текст?

2023-08-27 08:57 UTC, vadimrahmanov commented on index.html
> +        <a class="more-info" href="#"><b>ПОДРОБНЕЕ О НАС</b></a>
Устаревший тэг.

2023-08-27 08:57 UTC, vadimrahmanov commented on index.html
> +      <section class="contacts"> <!-- секция с контактами -->
![Screenshot 2023-08-27 at 09 18 26](https://github.com/htmlacademy-htmlcss/323345-device-1/assets/53314530/9184f9c4-7066-4415-b19e-1ac9e0464e2a)

Это всё одна секция. Нужно переделать.

2023-08-27 08:57 UTC, vadimrahmanov commented on index.html
> +          <p class="contacts-address-text"></p> Санкт-Петербург, набережная реки Карповки, 5, литера П.
Пустой параграф и рядом текст без тэга.

2023-08-27 08:57 UTC, vadimrahmanov commented on index.html
> +        </ul>
В названии класса слово `link`, хотя это не ссылки.

2023-08-27 08:57 UTC, vadimrahmanov commented on index.html
> +        <h3 class="distribution-h3">Подпишись на рассылку</h3>
Должен быть заголовок второго уровня

2023-08-27 08:57 UTC, vadimrahmanov commented on index.html
> +        <span class="free">Это бесплатно</span>
Это не элемент формы, поэтому должен быть снаружи формы.

2023-08-27 08:57 UTC, vadimrahmanov commented on index.html
> +      <a class="logo-device" href="#"><img src="image/content/logo-device-footer.png" alt="Логотип"></a>
Переносы.
Т.к мы уже на главной, куда обычно ведёт логотип, то можно убрать атрибут `href` здесь.
Также необходим текст для доступности.
У изображения неверный формат.

2023-08-27 08:57 UTC, vadimrahmanov commented on index.html
> +      </ol>
Переносы.
Неверный тип списка.

2023-08-27 08:57 UTC, vadimrahmanov commented on index.html
> +      </address>
Переносы.
Неверный тэг. Здесь не нужен `<address>`.
У ссылок должен быть текст для доступности.
Декоративные элементы (изображения соц. сетей) не нужно вставлять в разметку. Их потом с помощью CSS.
К тому же неверный формат у изображений.

2023-08-27 08:57 UTC, vadimrahmanov commented on index.html
> +      <a class="logo-academy" href="https://htmlacademy.ru/"><img src="image/content/logo-academy.png" alt="Логотип академии"></a>
Переносы.
Неверный формат изображения.
Должен быть текст у ссылки для доступности.
Атрибут `href` можно здесь убрать т.к обычно логотип ведёт на главную страницу, а мы уже на ней.

2023-08-27 08:57 UTC, vadimrahmanov commented on index.html
> +        <img src="image/content/delivery-man.png" alt="Доставщик" width="136" height="164">
Декоративное изображение. Нужно убрать из разметки.

2023-08-27 08:57 UTC, vadimrahmanov commented on index.html
> +        <img src="image/content/service.png" alt="Гарантия" width="171" height="195">
Декоративное изображение. Нужно убрать из разметки.

2023-08-27 08:57 UTC, vadimrahmanov commented on index.html
> +        <img src="image/content/credit.png" alt="Кредит" width="156" height="188">
Декоративное изображение. Нужно убрать из разметки.

2023-08-27 08:57 UTC, vadimrahmanov commented on catalog.html
> +    <h1 class="hidden">Интернет-магазин «Девайс»</h1>
Неверное название страницы. Это страницы Каталога, поэтому заголовок страницы должен об этом говорить.
Заголовок страницы должен быть сразу после открывающего тэга `<main>`.

2023-08-27 08:57 UTC, vadimrahmanov commented on catalog.html
> +                <a class="user-navigation-link" href="#"><img src="image/icon/user.svg" alt="Ваш ник">Коля Петухов</a>
декоративное изображение, ненужно вставлять в разметку.

2023-08-27 08:57 UTC, vadimrahmanov commented on catalog.html
> +      </header>
По `header` такие же замечания, что и на главной странице.

2023-08-27 08:57 UTC, vadimrahmanov commented on catalog.html
> +        <section class="breadcrumb">
Не увидел заголовка страницы `Моноподы для селфи`

2023-08-27 08:57 UTC, vadimrahmanov commented on catalog.html
> +          <h3 class="visually-hidden">Хлебные крошки</h3>
У секций всегда заголовок второго уровня.

2023-08-27 08:57 UTC, vadimrahmanov commented on catalog.html
> +          </ul>
Переносы.
У ссылок нету классов для стилизации.

2023-08-27 08:57 UTC, vadimrahmanov commented on catalog.html
> +            <input type="range" min="1" max="9000" value="5000">
Нету текста для поля. В макете написано `Стоимость`

2023-08-27 08:57 UTC, vadimrahmanov commented on catalog.html
> +        <aside class="checkbox">
Если используешь `aside`, то он должен быть в секции, к которой относится, а тут получается, что он как бы сам по себе.

И не совсем понятно название класса в этом случае.

2023-08-27 08:57 UTC, vadimrahmanov commented on catalog.html
> +            </ul>
Переносы.

2023-08-27 08:57 UTC, vadimrahmanov commented on catalog.html
> +                </form>
Здесь достаточно просто `select` без формы. Поправь переносы все.

2023-08-27 08:57 UTC, vadimrahmanov commented on catalog.html
> +            <li><a href="#" class="sort-down"><img src="image/icon/sort-down.svg" alt="down"></a></li>
Декоративные элементы не нужно вставлять в разметку в данном случае.
Нужен текст для доступности.
Это не ссылки ведущие на другие страницы, а кнопки.

2023-08-27 08:57 UTC, vadimrahmanov commented on catalog.html
> +          </ul>
Здесь не нужен список.

2023-08-27 08:57 UTC, vadimrahmanov commented on catalog.html
> +        </section>
Карточки с товарами ещё не начались, а секция уже закончилась.

2023-08-27 08:57 UTC, vadimrahmanov commented on catalog.html
> +            </table>
Здесь достаточно просто названия и цены. Таблицу необязательно в этом случае использовать.

2023-08-27 08:57 UTC, vadimrahmanov commented on catalog.html
> +          </div>
По карточкам одинаковое замечания про таблицу.

2023-08-27 08:57 UTC, vadimrahmanov commented on catalog.html
> +          <button type="submit">Загрузить еще</button>
`submit` только при отправке формы. Здесь не отправляем ничего.

2023-08-27 08:57 UTC, vadimrahmanov commented on catalog.html
> +          <button class="catalog-slider-button catalog-slider-prev" type="button">
А это как раз-таки ссылка, так как ведёт на следующую страницу.

2023-08-27 08:57 UTC, vadimrahmanov commented on catalog.html
> +          </ol>
Не нужно каждый элемент оборачивать с упорядоченный список. Это должен быть один список с элементами пагинации.
Используй здесь `ul`.

2023-08-27 08:57 UTC, vadimrahmanov commented on catalog.html
> +          <button class="catalog-slider-button catalog-slider-next" type="button">
Должна быть ссылка.

2023-08-27 08:57 UTC, vadimrahmanov commented on catalog.html
> +      </footer>
Те же замечания, что и на главной странице.

2023-08-27 08:57 UTC, vadimrahmanov commented on image/content/Credit.png
В названиях файлов нельзя использовать заглавные буквы, пробелы и т.п.

2023-08-27 08:57 UTC, vadimrahmanov commented on image/content/Delivery-man.png
В названиях файлов нельзя использовать заглавные буквы, пробелы и т.п.

2023-08-27 08:57 UTC, vadimrahmanov commented on image/content/VR-glasses-icon.svg
В названиях файлов нельзя использовать заглавные буквы, пробелы и т.п.

2023-08-27 08:57 UTC, vadimrahmanov commented on image/content/drone.png
у тебя два файла drone с разными форматами.

2023-08-29 10:32 UTC, licos87 commented on index.html
> +            </ul>
<pre><code>
&lt;ul class="visually-hidden"&gt;
         &lt;li class="catalog-link"&gt;
            &lt;a href="#"&gt;Виртуальная реальность&lt;/a&gt;
          &lt;/li&gt;
</code></pre>
в таком формате должно выглядеть?

2023-09-02 12:42 UTC, vadimrahmanov requested changes

2023-09-02 12:42 UTC, vadimrahmanov commented on index.html
> +        <div class="about-us">
У тебя у секции и у этого контейнера одинаковый класс. Можешь написать что-то типа `about-us-info`

2023-09-02 12:42 UTC, vadimrahmanov commented on index.html
> +            >
странные переносы

2023-09-02 12:42 UTC, vadimrahmanov commented on index.html
> +          <h3 class="contacts-subtitle">Время работы</h3>
Тут можешь `h4` использовать, так как у тебя `h3` уже используется как подзаголовки - О нас, Контакты

2023-09-02 12:42 UTC, vadimrahmanov commented on index.html
> +      <section class="distribution">
Это не `distribution`, а `newsletter` или `subscribe`

2023-09-02 12:42 UTC, vadimrahmanov commented on index.html
>        </section>
Поправь названия классов

2023-09-02 12:42 UTC, vadimrahmanov commented on index.html
> +      </ul>
Нужны классы. Например - `footer-navigation`

2023-09-02 12:42 UTC, vadimrahmanov commented on index.html
> +            <span class="visually-hidden">Ютуба</span>
Опечатка в слове `Ютуб`

2023-09-02 12:42 UTC, vadimrahmanov commented on catalog.html
> +          </li>
А на этой-то странице у тебя Коля Петухов и ссылка `Выйти` 😆

2023-09-02 12:42 UTC, vadimrahmanov commented on catalog.html
> +        <h2 class="visually-hidden">Хлебные крошки</h2>
Как думаешь, если спросить у человека, который не занимается веб-разработкой, что такое хлебные крошки, много кто ответит? 😆

2023-09-02 12:42 UTC, vadimrahmanov commented on catalog.html
> +        <ul class="breadcrumb">
`breadcrumbs`, множественное число

2023-09-02 12:42 UTC, vadimrahmanov commented on catalog.html
> +        </ul>
Поправь классы, чтобы отражали мн. число.

2023-09-02 12:42 UTC, vadimrahmanov commented on catalog.html
> +      <section class="product">
Здесь лучше использовать `products`

2023-09-02 12:42 UTC, vadimrahmanov commented on catalog.html
> +        <div class="checkbox">
Странное название класса. Можно заменить на `filter` .
Я писал про это в прошлый раз.

2023-09-02 12:42 UTC, vadimrahmanov commented on catalog.html
>              <h3>ФИЛЬТР</h3>
Слушай, забыл упомянуть одну вещь. Если видишь в макете текст написанный капсом, то пиши его нормально, не капсом. А уже потом через стили сделаешь его капсом. А то вдруг кто-то напишет так, а кто-то маленькими буквами, когда сайт будет в интернете. 

Пройдись по разметке всех страниц и поправь везде.

2023-09-02 12:42 UTC, vadimrahmanov commented on catalog.html
> +            <p class="price-chose">Стоимость</p>
У тебя ниже ведь поле. Значит тут будет семантичнее добавить `label` и привязать его к полю нижнему)

2023-09-02 12:42 UTC, vadimrahmanov commented on catalog.html
>            <form action="https://echo.htmlacademy.ru/courses" method="post"></form>
Неверный метод отправки. А также у тебя в конце открывающего тэга сразу закрывающий.

2023-09-02 12:42 UTC, vadimrahmanov commented on catalog.html
>            </form>
Задай для заголовков отделов один класс. Заголовки отделов - Стоимость, Цвет, Bluetooth.
Они у тебя все одинаковые.

2023-09-02 12:42 UTC, vadimrahmanov commented on catalog.html
> +        <div class="catalog-nav-title">
Честно говоря это название класса не несёт никакого смысла в данной ситуации

2023-09-02 12:42 UTC, vadimrahmanov commented on catalog.html
> +          <p>CОРТИРОВКА</p>  список не нужен
Напиши без капса. А то, что список не нужен необязательно пользователям сайта знать 😆

2023-09-02 12:42 UTC, vadimrahmanov commented on catalog.html
> +          </button>
Что значит up, down? Вот например слепой человек использует сайт с помощью читалки. Какой смысл несёт для него up, down? Тем более учитывая, что человек вряд-ли англоязычный.

2023-09-02 12:42 UTC, vadimrahmanov commented on catalog.html
> +        <div class="catalog">
Так, а вот такое название класса я уже видел на главной странице. Как ты будешь стилизовать?

2023-09-02 12:42 UTC, vadimrahmanov commented on catalog.html
> +            <span class="catalog-product-price">500 &#8381;</span>
Исправь на параграфы и оберни в `div`, будет проще стилизовать потом. Задай какой-нибудь класс обозначающий, что это информация о продукте/товаре.

2023-09-02 12:42 UTC, vadimrahmanov commented on catalog.html
>            </div>
Будет семантичнее, если ты все товары вынесешь в список, так как это список товаров по факту.

2023-09-02 12:42 UTC, vadimrahmanov commented on catalog.html
> +          <a class="previous">НАЗАД</a>
Напиши без капса. Добавь атрибут `href`

2023-09-02 12:42 UTC, vadimrahmanov commented on catalog.html
>            </button>
Какой-то закрывающий тэг тут отвалившийся

2023-09-02 12:42 UTC, vadimrahmanov commented on catalog.html
> +          <a class="next">ВПЕРЕД</a>
Нужно добавить атрибут и написать без капса.

2023-09-02 12:42 UTC, vadimrahmanov commented on catalog.html
>          </div>
Насчёт пагинации:

Вынеси полностью всю пагинацию в один контейнер вместе с ссылками `Назад`, `Вперёд`. Так как они тоже являются элементами пагинации.

2023-09-02 12:42 UTC, vadimrahmanov commented on catalog.html
> +          <span class="visually-hidden">Ютуба</span>
Опечатка в слове `Ютуб`.

2023-09-02 12:42 UTC, vadimrahmanov commented on catalog.html
> +      <ul class="social-icons">
Это же ведь ссылки на соц.сети, а не просто иконки

2023-09-02 12:42 UTC, vadimrahmanov commented on catalog.html
> +      </ul>
Нужны классы. Например - `footer-navigation`

2023-09-02 12:42 UTC, vadimrahmanov commented on image/content/Credit.png
В названиях файлов нельзя использовать заглавные буквы, пробелы и т.п.

2023-09-02 12:42 UTC, vadimrahmanov commented on image/content/Delivery-man.png
В названиях файлов нельзя использовать заглавные буквы, пробелы и т.п.

2023-09-02 12:42 UTC, vadimrahmanov commented on catalog.html
Страница не проходит валидацию W3C.

2023-09-14 10:41 UTC, vadimrahmanov requested changes

2023-09-14 10:41 UTC, vadimrahmanov commented on index.html
> +            <a class="navigation-link compare-header-link" href="#">Сравнить</a>
Классы на главной и на странице каталога должны быть одинаковые. Здесь неправильные. На странице каталога всё верно.

2023-09-14 10:41 UTC, vadimrahmanov commented on index.html
>                <h2 class="visually-hidden">Карточка товара</h2>
Должен быть заголовок третьего уровня как в первом слайде.

2023-09-14 10:41 UTC, vadimrahmanov commented on index.html
>                <h2 class="visually-hidden">Карточка товара</h2>
Должен быть заголовок третьего уровня как в первом слайде.

2023-09-14 10:41 UTC, vadimrahmanov commented on index.html
> +        <span class="trigger-text">Это бесплатно</span>
Что значит trigger-text?

2023-09-14 10:41 UTC, vadimrahmanov commented on index.html
> +        <form class="email-form" action="https://echo.htmlacademy.ru/" method="post">
Это не email-form, а newsletter-form. Следуй какой-то консистенции.

2023-09-14 10:41 UTC, vadimrahmanov commented on catalog.html
> +            <a class="navigation-link logoff-navigation-link" href="#"> Выйти</a>
`logout-navigation-link`

2023-09-14 10:41 UTC, vadimrahmanov commented on catalog.html
> +          <h3 class="filter-title">Сортировка:</h3>
У тебя по макету другие стили здесь, не такие как выше с классом .filter-title

2023-09-14 10:41 UTC, vadimrahmanov commented on catalog.html
> +        <div class="sort-title">
это не заголовок, это контейнер куда вложено много других элементов.

2023-09-14 10:41 UTC, vadimrahmanov commented on catalog.html
> +          <div class="slider-pagination">
Это не слайдер вовсе.

2023-09-14 10:41 UTC, vadimrahmanov commented on catalog.html
> +              <div class="catalog-item">
Почему здесь класс item, а выше items? нужно исправить для всех карточек.

2023-09-15 06:30 UTC, licos87 commented on index.html
> +            <a class="navigation-link compare-header-link" href="#">Сравнить</a>
![2023-09-15_09-28-40](https://github.com/htmlacademy-htmlcss/323345-device-1/assets/23637553/b6b136f4-1449-4115-aeb3-ea3e2c9125ab)
![2023-09-15_09-28-29](https://github.com/htmlacademy-htmlcss/323345-device-1/assets/23637553/23d80d3a-30b3-4dad-bd28-802f060facf2)
Что-то я нифига не понял)

2023-09-15 06:57 UTC, licos87 commented on catalog.html
> +          <h3 class="filter-title">Сортировка:</h3>
<h3 class="filter-title">Фильтр:</h3>
<h3 class="filter-title">Сортировка:</h3>
![2023-09-15_09-56-39](https://github.com/htmlacademy-htmlcss/323345-device-1/assets/23637553/3cc54c88-b327-4769-ad98-3a4ae084beff)
![2023-09-15_09-56-20](https://github.com/htmlacademy-htmlcss/323345-device-1/assets/23637553/514e67f2-04bc-43e5-8397-c145aedb76cf)
Опять не понял.

2023-09-18 05:34 UTC, vadimrahmanov approved these changes

2023-09-18 05:34 UTC, vadimrahmanov commented on catalog.html
> +          <h3 class="filter-title">Сортировка:</h3>
Извини, перепутал с filter-item.

2023-09-18 05:34 UTC, vadimrahmanov commented on catalog.html
> +              <div class="catalog-cards">
Лучше бы ты заменил items. В общем исправь классы, чтобы было единственное число, а не множественное.

2023-09-18 05:34 UTC, merged