Д.з. Базовая стилизация всех страниц.
htmlacademy-htmlcss/323345-device-1 pull request #5
Opened 2023-09-22 11:26 UTC by licos87

2023-09-26 08:05 UTC, vadimrahmanov requested changes

2023-09-26 08:05 UTC, vadimrahmanov commented on styles/styles.css
> +  margin-right: -10px;
нежелательно использовать отрицательные значения

2023-09-26 08:05 UTC, vadimrahmanov commented on styles/styles.css
> +  height: 174px;
Никогда не задавай фиксированную высотку (кроме изображений), т.к если добавится ещё текст, то он выпадет из элемента. Это касается всех мест, где у тебя фиксированная высота (кроме изображений.)

2023-09-26 08:05 UTC, vadimrahmanov commented on styles/styles.css
> +  height: 40px;
убери фикс. высоту

2023-09-26 08:05 UTC, vadimrahmanov commented on styles/styles.css
> +.popular-chose{
пробел после названия класса

2023-09-26 08:28 UTC, licos87 commented on styles/styles.css
> +  line-height: normal;
А вот тут вопрос, я так и не понял какое это значение,  line-height: normal
из-за этого так и написал

2023-09-26 17:08 UTC, licos87 commented on styles/styles.css
> +  margin-right: -10px;
А как надвинуть span на корзину?)

2023-10-05 08:22 UTC, vadimrahmanov approved these changes

2023-10-05 08:22 UTC, merged